### ISSUE TITLE
built-in colour scheme is terrible for white background

### ISSUE THREAD

**Issue by jwaldmann** [cdepillabout/pretty-simple#10]
try running this in a terminal with a "black letters on white background" setting. (In particular,
this is what I use in presentations/teaching, with a projector.)

* string quotes are white? - completely invisible.
* some parentheses are yellow - nearly invisible.

perhaps make an extra function (pPrintOnWhite).

**Comment by cdepillabout** [comment]
You're right about this.  The colors are currently hard-coded, so I'll make them able to be changed dynamically.

I'll then go and add functions like `pPrintOnDarkBg`, `pPrintOnLightBg`, etc.  I'll probably have `pPrint` just call `pPrintOnDarkBg`.

If you have any opinion on what the names should be, let me know.

**Comment by cdepillabout** [comment]
I've added additional functions for printing on a console with a light background and released a new version to hackage.  You can find it here:

https://hackage.haskell.org/package/pretty-simple-2.0.0.0

Feel free to reopen this if you have any suggestions/comments.
