### ISSUE TITLE
Add `pTraceWith`

### ISSUE THREAD

**Issue by georgefst** [cdepillabout/pretty-simple#100]
If https://github.com/haskell/core-libraries-committee/issues/36 gets accepted (and arguably, even if it doesn't), we should add analogous functions to `Debug.Pretty.Simple`.

I end up defining `traceShowWith`/`pTraceShowWith` myself all the time. It's a very useful function.

**Comment by cdepillabout** [comment]
This looks like it was closed in #104.

Thanks!
