### ISSUE TITLE
Add "deprecation" warnings to `Debug.Pretty.Simple`?

### ISSUE THREAD

**Issue by georgefst** [cdepillabout/pretty-simple#101]
[`protolude` does this](https://hackage.haskell.org/package/protolude-0.3.0/docs/Protolude-Debug.html) and it's very nice to get warnings showing you exactly where in your code you've left debugging artefacts.

IIRC, Elm also does something similar (in a slightly more ad-hoc way), as presumably do some other languages/compilers.

**Comment by chaughawout** [comment]
Hey @georgefst do ya'll typically close issues once the PR is merged or once the module is published?

**Comment by georgefst** [comment]
The former. Thanks for reminding me.
