### ISSUE TITLE
Hexdecimal Regression between 3.3 and 4.0

### ISSUE THREAD

**Issue by andrewthad** [cdepillabout/pretty-simple#102]
In 3.3 and earlier, `pretty-simple` kept hexadecimal numbers as a single token:

    0xbb

The new behavior is this:

    0 xbb

I found this because a spec test that relied on the old behavior started failing.

**Comment by georgefst** [comment]
This is unfortunately a known issue, which may require significant changes to our parser.

Closing in favour of #75.

**Comment by georgefst** [comment]
Fortunately there's nothing much wrong with 3.3. 4.0 adds features rather than fixing any bugs.
