### ISSUE TITLE
Empty string in `stdout` instead of using handle

### ISSUE THREAD

**Issue by Lev135** [cdepillabout/pretty-simple#114]
As far as I understood `pHPrint` prints `eoln` at the end using `putStrLn`, not in handle. It was very suprising for me. Why it's do so? Is it a bug or a feature?

```
pHPrintStringOpt checkColorTty outputOptions Handle
handle str = do
  realOutputOpts <-
    case checkColorTty of
      CheckColorTty -> hCheckTTY handle outputOptions
      NoCheckColorTty -> pure outputOptions
  liftIO $ do
    renderIO handle $ layoutStringAnsi realOutputOpts str
    putStrLn ""
```
I've found it while rendering in file using `pHPrint` and these empty lines surprised me

**Comment by cdepillabout** [comment]
@Lev135 Thanks for submitting this issue!

This is very likely a bug.  Would you be able to send a PR fixing this?
