### ISSUE TITLE
make more newlines in the output

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/pretty-simple#17]
The output is pretty hard to read when there are not enough newlines.

![bad-formatting](https://cloud.githubusercontent.com/assets/64804/26457774/4e92ee4a-41ac-11e7-8a87-3871d4174a40.png)

Everything after `TypeDeclaration` should really have newlines.

**Comment by andrew-lei** [comment]
Should there be a newline for every paren/bracket/brace layer?

**Comment by cdepillabout** [comment]
@andrew-lei To be honest, I haven't thought about this hard enough to figure out exactly what the rules should be on when to create newlines.

I think the current rules are something like the following:

- *Create a newline whenever there are commas separating child elements.*
- *If one of your inner children has newlines, then add a newline before displaying it.*

In the picture above, I think the reason that nothing after `TypeDeclaration` has a newline is that there are no commas separating values.  This is not ideal, because it is hard to read.

In order to solve this problem, we would need to come up with a good algorithm for when to insert newlines.  We then need to come up with a couple doctests to test this.

We could look at code formatting tools like [hindent](https://github.com/commercialhaskell/hindent) or brittany](https://github.com/lspitzner/brittany) to figure out when they add new lines, and basically just copy how they do it.

**Comment by andrew-lei** [comment]
I think perhaps alternatively:

- create new line if next later contains comma-separated values
- create new line if next layer contains layer of its own

Then `A ( A B )` stays `A ( A B )` (since it's a bit unnecessary to do a newline here), but `A ( A ( A B ) )` becomes

```
A
    ( A ( A B ) )
```

and `A ( A ( A ( A B ) ) )` becomes

```
A
    ( A
        ( A ( A B ) )
    )
```

**Comment by andrew-lei** [comment]
If I'm reading [this](https://github.com/lspitzner/brittany/blob/master/doc/implementation/theory.md) correctly, it looks like brittany keeps track of how many columns are used. That does sound like a pretty good idea, although it seems like that would require a bit more work. One of the other solutions could work in the meantime and would only require a couple lines of code to be different (other than docstrings I guess), unless you'd rather hold off for a solution like that.
