### ISSUE TITLE
Get rid of the `mono-traversable` dependency

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/pretty-simple#2]
Ideally, `pretty-simple` would have as few dependencies as possible.

`mono-traversable` was used during development of `pretty-simple` to make development go faster, but it should not actually be needed.

Specific functions from `Data.List`, `Data.Sequence`, `Data.Text`, etc should be used instead of the generic functions from `mono-traversable`.

**Comment by tebello-thejane** [comment]
Please see pull request #13. :-)

**Comment by cdepillabout** [comment]
Thanks again!
