### ISSUE TITLE
use a state monad for keeping track of the output state

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/pretty-simple#25]
I talked a little about this in my response in #24.

This would look similar to how it is done in [hindent](https://github.com/commercialhaskell/hindent/blob/1e8b036c41fdf517fdb40f06bd1d60a6a95c4393/src/HIndent/Types.hs#L33-L57).

**Comment by sureyeaah** [comment]
Hey, I would like to work on this. Any particular things I should keep in mind?

**Comment by cdepillabout** [comment]
@sureyeaah Thanks for taking a look at this!

> Any particular things I should keep in mind?

I'd take a glance at the [hindent source code](https://github.com/chrisdone/hindent/blob/1e8b036c41fdf517fdb40f06bd1d60a6a95c4393/src/HIndent/Types.hs#L33-L57) and see how it uses `StateT` (in its `Printer` newtype).  I think a similar thing could be done for the pretty-simple output code.

Also, the printing code for pretty-simple is pretty hacky, so feel free to make big changes.

There are lots(?) of tests for pretty-simple, so you should feel confident in making changes.

**Comment by cdepillabout** [comment]
@sureyeaah Oh, I did think of one this you should keep in mind.

pretty-simple is able to parse and pretty-print lazy data structures, so it is important that this property is kept.

When you are working on this, just make sure that pretty-printing lazy data structures (like `[1..]`) still works.

**Comment by sureyeaah** [comment]
The ExprToOutput module uses a state monad already. Where exactly is it that we need to make changes then?

**Comment by cdepillabout** [comment]
@sureyeaah The [`Text.Pretty.Simple.Internal.OutputPrinter`](https://github.com/cdepillabout/pretty-simple/blob/7f91debd52b6208de62890cc6525fe968ba86b60/src/Text/Pretty/Simple/Internal/OutputPrinter.hs) module contains the [`render`](https://github.com/cdepillabout/pretty-simple/blob/7f91debd52b6208de62890cc6525fe968ba86b60/src/Text/Pretty/Simple/Internal/OutputPrinter.hs#L126) function, which turns a list of `Output` elements into `Text`.

It does this by writing to a `Text.Builder` directly.  Instead, it would probably be easier to use a `State` monad, similar to the `ExprToOutput` module.  This should also be similar to other Haskell pretty-printing libraries, like `hindent`.

**Comment by cdepillabout** [comment]
Another thing that might help simplify this is actually using a proper pretty-printing library:

https://hackage.haskell.org/package/prettyprinter

Although a big thing to keep in mind is whether this would be sufficiently lazy.

**Comment by sjakobi** [comment]
> Another thing that might help simplify this is actually using a proper pretty-printing library:
> 
> https://hackage.haskell.org/package/prettyprinter

Oh, no! ;)

I actually rely on `pretty-simple` to [debug](https://github.com/quchen/prettyprinter/blob/ff555e19b7b17a74f16e6fb062256a57dabe4d92/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal/Debug.hs#L7-L22) `prettyprinter`. This would introduce a circular dependency!

(I could probably work around a circular dependency though…)

**Comment by sjakobi** [comment]
Note BTW that there's already

http://hackage.haskell.org/package/show-prettyprint

which is a bit like a `pretty-simple` built on top of `prettyprinter`. I think its output is less nice than `pretty-simple`'s though.

**Comment by cdepillabout** [comment]
Ah, I see :-)

I guess keeping the dependencies of `pretty-simple` minimal would be a good idea, so maybe using a different pretty-printing library, or re-implementing a simple pretty-printing library in `pretty-simple` would make sense.

**Comment by georgefst** [comment]
@sjakobi out of interest, would you be able to get away with:

`cab install pretty-simple -f buildexe`

```haskell
pp :: Show a => a -> IO ()
pp = putStrLn <=< readProcess "pretty-simple" [] . show
```

I've used this trick before to avoid actually depending on `pretty-simple`.

I think there's a reasonable argument for using an actual pretty-printing library, and `prettyprinter` itself has minimal dependencies.

**Comment by georgefst** [comment]
Anyway, @sureyeaah, did you make any progress here?

I figure it may simplify #66, as well as the existing #56 and #43.

**Comment by sjakobi** [comment]
@georgefst Thanks, that looks like a nice trick!

I think I can also recommend using `prettyprinter` at this stage. It's pretty polished and there are no plans to adopt any dependencies that aren't core libraries. There have even been some ideas to somewhat "standardize" its use, so libraries like `ansi-wl-pprint` could eventually be deprecated.
