### ISSUE TITLE
Consider switching to 'megaparsec' from 'parsec'

### ISSUE THREAD

**Issue by ChShersh** [cdepillabout/pretty-simple#29]
Difference from `parsec`:

* https://github.com/mrkkrp/megaparsec#megaparsec-vs-parsec

**Comment by cdepillabout** [comment]
Hi @ChShersh, thanks for opening this issue.

I would be willing to merge a PR switching from parsec to megaparsec.

I've personally never used megaparsec in a project before, but I have had it on my radar for a while.

**Comment by cdepillabout** [comment]
The latest release of pretty-simple actually removed the dependency on parsec and instead just wrote the lexer by hand: #37 

I'll go ahead and close this issue.

I'm not sure if the current lexer code could be made simpler by using a parsing library, but if so then someone could feel free to reopen this issue.
