### ISSUE TITLE
Get rid of the `lens` dependency

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/pretty-simple#3]
Ideally, `pretty-simple` would have as few dependencies as possible.

`lens` was used during development of `pretty-simple` to make development go faster, but it should not actually be needed.

Here's three different ideas for getting rid of the `lens` dependency:

1. Just remove all lenses.  Use regular functions.
2. Use a smaller lens library, like [microlens](https://hackage.haskell.org/package/microlens) and [microlens-mtl](https://hackage.haskell.org/package/microlens-mtl).
3. Have our own _very-small_ lens library inside of `pretty-simple`.

**Comment by tebello-thejane** [comment]
Hey. :-)

I hope https://github.com/cdepillabout/pretty-simple/pull/11 is good enough? :-)

**Comment by cdepillabout** [comment]
Thanks!  It's a big help :-)
