### ISSUE TITLE
The parser fails to parse strings with escaped quotation marks

### ISSUE THREAD

**Issue by anka-213** [cdepillabout/pretty-simple#40]
Currently, escaped quotation marks within strings are interpreted as the end of a string.
For example, if show gave this:

    Foo "hello \" world!"

The parser would give back:

    > parseExprs "Foo \"hello \\\"world!\""
    ([Other "Foo ",StringLit "hello \\",Other "world!",StringLit ""],"")

instead of the expected

    ([Other "Foo ",StringLit "hello \\\" world!"],"")

**Comment by dminuoso** [comment]
Would be great if you could push 2.2.0.1 to hackage to include this fix. :)

**Comment by cdepillabout** [comment]
@dminuoso Pushed it to Hackage!

https://hackage.haskell.org/package/pretty-simple-2.2.0.1
