### ISSUE TITLE
the parser doesn't understand Haskell characters like 'a'

### ISSUE THREAD

**Issue by neongreen** [cdepillabout/pretty-simple#45]
```
Text.Pretty.Simple> pStringNoColor "[']']"
"[ ' ]'"
```

The correct output should be `"[']'"`.

**Comment by cdepillabout** [comment]
@neongreen I think the problem with pretty-simple is two-fold:

1. pretty-simple doesn't handle non-balanced brackets: #27.  Here's the expression that `"[']']"` is parsed into:

    ```haskell
    [ Brackets 
        ( CommaSeparated 
            { unCommaSeparated = 
                [ [ Other "'" ] ]
            }
        )
    , Other "'" 
    ]
    ```

    Basically this means there are brackets surrounding a `'`, and then a single `'`.  The final bracket is removed.  The reason there is are spaces around the first quote is that pretty-simple prints spaces inside of brackets by default.

1. pretty-simple doesn't have a special parser for Haskell characters (e.g. things like `'a'` or `'X'` or `']'`).  So it doesn't realize that `]` is supposed to be a character (and not a closing bracket).

If you want to send a PR fixing either of these things, it would definitely be accepted!

**Comment by sjakobi** [comment]
> ```
> Text.Pretty.Simple> pStringNoColor "[']']"
> "[ ' ]'"
> ```
> 
> 
> The correct output should be `"[']'"`.

Should that be `"[ ']' ]"` in analogy to

```
> pStringNoColor "[1]"
"[ 1 ]"
```

?
