### ISSUE TITLE
add pPrintString function

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/pretty-simple#53]
Often I want a function like the following:

```haskell
pPrintString :: MonadIO m => String -> m ()
```

This would be similar to `pPrint` and `pString`.

`pPrint` actually prints out something `Show`able to the console, while `pString` takes a haskell datatype that has been `show`ed and pretty prints it to a `Text`.

`pPrintString` would take a Haskell datatype that has already been `show`ed and pretty prints it to the screen.

**Comment by sureyeaah** [comment]
I'd like to work on this :)

**Comment by cdepillabout** [comment]
@sureyeaah Thanks! Please go ahead!
