### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by sjakobi** [cdepillabout/pretty-simple#61]
```haskell
> pPrintString "Union (Cat (Char 'x') Fail) (Cat (Char 'x') Line)"
Union 
    ( Cat ( Char 'x' ) Fail ) 
    ( Cat ( Char 'x' ) Line )
```

There's a trailing space character both on the first and second line. It would be nice if `pretty-simple` wouldn't do this, although it hasn't been a big problem for me so far.

**Comment by cdepillabout** [comment]
I totally agree with this.

I believe the pretty-printer needs to be a little smarter here.

The following issue talks about improving the output printer.  If this was completed, removing trailing whitespace might be easier: https://github.com/cdepillabout/pretty-simple/issues/25
