### ISSUE TITLE
Parsing data constructors with quotes

### ISSUE THREAD

**Issue by georgefst** [cdepillabout/pretty-simple#63]
``` haskell
data Tree' a = Leaf' a | Node' (Tree' a) (Tree' a) deriving Show

t1 :: Tree' Int
t1 = Node' (Leaf' 1) (Leaf' 2)
```

`pPrint t1` produces `Node' (Leaf' 1`, with the colouring also messed up.

This is rather a shame, as using `T'` for a structure similar to `T` is a pretty common haskell idiom.

**Comment by cdepillabout** [comment]
@georgefst Thanks for creating this issue.

I'd be happy to merge in a PR fixing this if you wanted to take a shot at it.

Or, if you wanted to run a `git bisect` and figure out where this was introduced, it might help someone else figure out how this can be fixed.

Without actually looking into it at all, my guess is that this was introduced by https://github.com/cdepillabout/pretty-simple/pull/57.  (ping @sjakobi just in case)

**Comment by georgefst** [comment]
Just checked and it works correctly with the 3.1.1.0 release, so that looks very likely.

I may look into this on the weekend, but I've got quite a backlog at the moment.
