### ISSUE TITLE
Indent whole expression

### ISSUE THREAD

**Issue by georgefst** [cdepillabout/pretty-simple#66]
I've often found myself wanting to indent a pretty-printed expression in it's entirety, e.g. when surrounding it by other text, as part of an error output.

Would you accept a PR that added an `outputOptionsInitialIndent` field (feel free to bikeshed the name) to `OutputOptions`?

I haven't yet looked at the code, but I imagine #25 would make this very easy, if it isn't already, as it would just amount to running with a non-zero in the initial state.

**Comment by cdepillabout** [comment]
@georgefst Yeah, this sounds good to me!

You'll have to look through the logic in `src/Text/Pretty/Simple/Internal/OutputPrinter.hs` to see if there is an easy place to indent every line.

Although, I also agree that doing this after #25 would probably be much easier, so if you are interested in implementing #25 first, please go ahead.

**Comment by georgefst** [comment]
I'm starting to think that using `prettyprinter` may be the cleaner solution, as discussed in that thread. So I think I'll experiment with that, if you approve.

Obviously that's a fairly sizeable change - how good is the test coverage?

**Comment by cdepillabout** [comment]
Yeah, I agree that using another package to help with outputting would be a good idea.

I don't really know the various choices, but it sounds like `prettyprinter` works well, so I'd be interested in seeing a solution using that (or even another library if you decide there is a better one).

> how good is the test coverage?

The test coverage is okay-ish.

There are tests in `src/Text/Pretty/Simple/Internal/OutputPrinter.hs` that you saw, as well as a bunch of examples at the bottom of `src/Text/Pretty/Simple.hs`.  Feel free to add more tests to make this task easier.

**Comment by georgefst** [comment]
`prettyprinter` is more or less the de facto standard (it's certainly [very widely used](https://packdeps.haskellers.com/reverse/prettyprinter)), so I think I'll stick with that.

**Comment by sjakobi** [comment]
@georgefst BTW, if you find any difficulties in using `prettyprinter`, please do report them on the issue tracker. I'm quite keen on making it easier to adopt and easier to use.

**Comment by georgefst** [comment]
@sjakobi Will do.

FWIW, I've used it previously for a large project at work (and ended up extracting [a library](http://hackage.haskell.org/package/prettyprinter-graphviz) from that), and I've had no issues thus far.
