### ISSUE TITLE
advertise that this can be integrated with ghci

### ISSUE THREAD

**Issue by jwaldmann** [cdepillabout/pretty-simple#8]
you can do this:
```
ghci -interactive-print=Text.Pretty.Simple.pPrint
```
then every output in a ghci session will be pretty-printed, see https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html#using-a-custom-interactive-printing-function

(when I read the original accouncement, I thought this was the main purpose, but I do not find this mentioned in the docs)

**Comment by cdepillabout** [comment]
Thanks for letting me know about this feature!  This is pretty handy.  I added a note to the README:

https://github.com/cdepillabout/pretty-simple#pretty-print-all-ghci-output
