### ISSUE TITLE
please add latest to stackage

### ISSUE THREAD

**Issue by simonmichael** [cdepillabout/pretty-simple#88]
Thanks for pretty-simple!

The september release (4.0.0) is not yet in stackage. It would be great if it (and the prettyprinter dep) could be [added](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package), simplifying installation of apps using pretty-simple.

**Comment by cdepillabout** [comment]
@simonmichael No problem!

I've tried to keep pretty-simple in Stackage, but I didn't realize it had been removed.

**Comment by cdepillabout** [comment]
Oh, looks like there was a message: https://github.com/commercialhaskell/stackage/issues/5772

**Comment by cdepillabout** [comment]
simonmichael did this in  commercialhaskell/stackage#5775. Thanks!
