### ISSUE TITLE
Numbers (prefixed with 0x) have a space put between 0 and x

### ISSUE THREAD

**Issue by expipiplus1** [cdepillabout/pretty-simple#89]
```
λ> pStringNoColor "0x0"
"0 x0"
```

**Comment by georgefst** [comment]
This is another instance of #75, which is increasingly looking like a priority.

**Comment by expipiplus1** [comment]
Is it a duplicate? That seems to be dealing with spaces around operators, but this is a valid Haskell numeric literal being mangled (albeit one which isn't generated by derived show instances).

**Comment by georgefst** [comment]
It has the same root cause, and solution.

**Comment by expipiplus1** [comment]
Sure, but I think fixing this would be much less controversial than the
operator space case.

Either way it looks like the spaces will be removed so no biggie.

(I wonder if scientific notation suffers too, 10e5 etc..)
