### ISSUE TITLE
cabal new-repl: Pretty-print all GHCi output

### ISSUE THREAD

**Issue by benjaminweb** [cdepillabout/pretty-simple#92]
The README gives the instructions to pPrint GHCi output by default with stack.
How is it done with cabal new-repl?

```
cabal new-repl --ghci-options "-interactive-print=Text.Pretty.Simple.pPrint" --package pretty-simple
cabal: unrecognized 'new-repl' option `--ghci-options'
unrecognized 'new-repl' option `-interactive-print=Text.Pretty.Simple.pPrint'
```

**Comment by cdepillabout** [comment]
@benjaminweb I don't actually use `cabal` very much, but it looks like `cabal new-repl` (or, well, now just `cabal repl`) has a flag `--repl-options`.  I imagine this is the same as stack's `--ghci-options`.

I'd really appreciate if you could figure this out and send a PR updating the README.  I'm sure that would be helpful for other people!

**Comment by benjaminweb** [comment]
> cabal new-repl --repl-options "-interactive-print=Text.Pretty.Simple.pPrint" --package pretty-simple

does work for me. Will consider a PR.
